import json
from typing import Any

from fastapi import HTTPException

try:
    from .config import Settings, get_settings
    from .llm_client import SERVICE_FALLBACK_MESSAGE, call_llm
    from .models import SqlGenerationResult
    from .prompts import SQL_REPAIR_PROMPT, SQL_SYSTEM_PROMPT
except ImportError:  # pragma: no cover
    from config import Settings, get_settings
    from llm_client import SERVICE_FALLBACK_MESSAGE, call_llm
    from models import SqlGenerationResult
    from prompts import SQL_REPAIR_PROMPT, SQL_SYSTEM_PROMPT


class SqlGenerator:
    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()
        self._sql_cache: dict[str, SqlGenerationResult] = {}

    def generate(
        self,
        *,
        user_query: str,
        provider: str,
        semantic_summary: str,
        schema_overview: list[dict[str, Any]],
        schema_tables: list[str],
        table_hint: str | None,
        context: dict[str, Any],
    ) -> SqlGenerationResult:
        if provider.lower() == "rules":
            return self._generate_with_rules(
                user_query=user_query,
                semantic_summary=semantic_summary,
                schema_overview=schema_overview,
                schema_tables=schema_tables,
                table_hint=table_hint,
            )

        cache_key = self._build_cache_key(
            user_query=user_query,
            context=context,
            semantic_summary=semantic_summary,
            table_hint=table_hint,
        )
        cached = self._sql_cache.get(cache_key)
        if cached is not None:
            return cached.model_copy(deep=True)

        try:
            sql = self.generate_sql(
                query=user_query,
                schema=schema_overview,
                table_hint=table_hint,
            )
            result = SqlGenerationResult(
                sql=sql,
                assumptions=["Generated by Gemini using the provided schema and semantic hints."],
            )
            self._sql_cache[cache_key] = result
            return result.model_copy(deep=True)
        except HTTPException as exc:
            if exc.status_code == 429:
                fallback = self._generate_with_rules(
                    user_query=user_query,
                    semantic_summary=semantic_summary,
                    schema_overview=schema_overview,
                    schema_tables=schema_tables,
                    table_hint=table_hint,
                )
                fallback.assumptions.append("Gemini quota was exceeded, so QueryEase used its local fallback generator.")
                return fallback
            raise

    def generate_sql(self, query: str, schema: list[dict[str, Any]], table_hint: str | None = None) -> str:
        prompt = self._build_generate_prompt(
            query=query,
            schema=schema,
            table_hint=table_hint,
        )
        return self._normalize_sql(call_llm(prompt, settings=self.settings))

    def repair(
        self,
        *,
        user_query: str,
        provider: str,
        failed_sql: str,
        error_message: str,
        semantic_summary: str,
        schema_overview: list[dict[str, Any]],
        schema_tables: list[str],
        table_hint: str | None,
        context: dict[str, Any],
    ) -> SqlGenerationResult:
        if provider.lower() == "rules":
            return self._repair_with_rules(
                user_query=user_query,
                failed_sql=failed_sql,
                error_message=error_message,
                semantic_summary=semantic_summary,
                schema_overview=schema_overview,
                schema_tables=schema_tables,
                table_hint=table_hint,
            )

        prompt = self._build_repair_prompt(
            user_query=user_query,
            failed_sql=failed_sql,
            error_message=error_message,
            context=context,
            semantic_summary=semantic_summary,
            schema_overview=schema_overview,
            table_hint=table_hint,
        )
        try:
            sql = self._normalize_sql(call_llm(prompt, settings=self.settings))
            return SqlGenerationResult(
                sql=sql,
                assumptions=["Repaired by Gemini using the database error, schema, and semantic hints."],
            )
        except HTTPException as exc:
            if exc.status_code == 429:
                fallback = self._repair_with_rules(
                    user_query=user_query,
                    failed_sql=failed_sql,
                    error_message=error_message,
                    semantic_summary=semantic_summary,
                    schema_overview=schema_overview,
                    schema_tables=schema_tables,
                    table_hint=table_hint,
                )
                fallback.assumptions.append("Gemini quota was exceeded during repair, so QueryEase used its local fallback repair.")
                return fallback
            raise

    def _normalize_sql(self, raw_output: str) -> str:
        sql = raw_output.strip()

        if sql == SERVICE_FALLBACK_MESSAGE:
            raise HTTPException(status_code=429, detail={"message": SERVICE_FALLBACK_MESSAGE})

        if sql.startswith("```"):
            lines = sql.splitlines()
            if lines:
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            sql = "\n".join(lines).strip()

        if sql.lower().startswith("sql\n"):
            sql = sql[4:].strip()

        if not sql:
            raise HTTPException(
                status_code=502,
                detail={"message": "LLM response did not include a valid SQL statement.", "raw": raw_output},
            )

        return sql.rstrip(";")

    def _build_generate_prompt(
        self,
        *,
        query: str,
        schema: list[dict[str, Any]],
        table_hint: str | None,
    ) -> str:
        compact_query = query.strip()[: self.settings.max_query_length]
        formatted_schema = self._format_schema(schema)
        hint_line = table_hint or "none"
        return (
            f"{SQL_SYSTEM_PROMPT}\n\n"
            "CONTEXT:\n"
            f"Database schema:\n{formatted_schema}\n\n"
            f"User likely refers to table: {hint_line}\n\n"
            "USER QUERY:\n"
            f"{compact_query}\n\n"
            "OUTPUT:\n"
            "Return ONLY SQL query"
        )

    def _build_repair_prompt(
        self,
        *,
        user_query: str,
        failed_sql: str,
        error_message: str,
        context: dict[str, Any],
        semantic_summary: str,
        schema_overview: list[dict[str, Any]],
        table_hint: str | None,
    ) -> str:
        compact_query = user_query.strip()[: self.settings.max_query_length]
        compact_error = " ".join(error_message.split())[:300]
        hint_line = table_hint or "none"
        return (
            f"{SQL_REPAIR_PROMPT}\n\n"
            f"User likely refers to table: {hint_line}\n\n"
            "Original user request:\n"
            f"{compact_query}\n\n"
            "You generated this SQL:\n"
            f"{failed_sql}\n\n"
            "Issue:\n"
            f"{compact_error or 'empty result'}\n\n"
            "Schema:\n"
            f"{self._format_schema(schema_overview)}\n\n"
            "Fix the SQL query.\n"
            "Return ONLY SQL."
        )

    def _format_schema(self, schema_overview: list[dict[str, Any]]) -> str:
        if not schema_overview:
            return "No schema overview available."

        formatted_tables: list[str] = []
        for table in schema_overview[: self.settings.prompt_table_limit]:
            table_name = str(table.get("table", "unknown_table"))
            columns = table.get("columns", [])[: self.settings.prompt_column_limit]

            if isinstance(columns, list):
                column_items = []
                for column in columns:
                    if isinstance(column, dict):
                        column_name = str(column.get("name", "unknown_column"))
                        column_items.append(column_name)
                    else:
                        column_items.append(str(column))
                columns_text = ", ".join(column_items) if column_items else "no columns listed"
            else:
                columns_text = str(columns)

            formatted_tables.append(f"{table_name}: {columns_text}")

        return "\n".join(formatted_tables)

    def _format_context(self, context: dict[str, Any]) -> str:
        if not context:
            return "none"

        compact_items = list(context.items())[:5]
        return "; ".join(f"{key}={value}" for key, value in compact_items)

    def _generate_with_rules(
        self,
        *,
        user_query: str,
        semantic_summary: str,
        schema_overview: list[dict[str, Any]],
        schema_tables: list[str],
        table_hint: str | None,
    ) -> SqlGenerationResult:
        lowered = user_query.lower()
        table_name = self._resolve_fallback_table(
            table_hint=table_hint,
            semantic_summary=semantic_summary,
            schema_overview=schema_overview,
            schema_tables=schema_tables,
        )
        if "count" in lowered or "how many" in lowered:
            sql = f"SELECT COUNT(*) AS total_rows FROM {table_name}"
            assumptions = ["Used a count query because the request asked for totals."]
        elif "latest" in lowered or "recent" in lowered:
            sql = f"SELECT * FROM {table_name} ORDER BY 1 DESC LIMIT 200"
            assumptions = ["Used the first column for recent ordering because no timestamp column was confirmed."]
        else:
            sql = f"SELECT * FROM {table_name} LIMIT 200"
            assumptions = ["Returned a sample result set because the rules provider is active."]

        return SqlGenerationResult(sql=sql, assumptions=assumptions)

    def _repair_with_rules(
        self,
        *,
        user_query: str,
        failed_sql: str,
        error_message: str,
        semantic_summary: str,
        schema_overview: list[dict[str, Any]],
        schema_tables: list[str],
        table_hint: str | None,
    ) -> SqlGenerationResult:
        table_name = self._resolve_fallback_table(
            table_hint=table_hint,
            semantic_summary=semantic_summary,
            schema_overview=schema_overview,
            schema_tables=schema_tables,
        )
        if (
            table_hint
            or "doesn't exist" in error_message.lower()
            or "unknown column" in error_message.lower()
            or "invalid table" in error_message.lower()
            or "expected sql to use detected table" in error_message.lower()
        ):
            sql = f"SELECT * FROM {table_name} LIMIT 200"
            assumptions = ["Fell back to a basic table sample using the enforced table selection."]
        else:
            sql = failed_sql
            assumptions = [f"Rules provider could not improve the query beyond the last attempt for: {user_query}"]

        return SqlGenerationResult(sql=sql, assumptions=assumptions)

    def _resolve_fallback_table(
        self,
        *,
        table_hint: str | None,
        semantic_summary: str,
        schema_overview: list[dict[str, Any]],
        schema_tables: list[str],
    ) -> str:
        if table_hint:
            return table_hint

        semantic_table = self._extract_table_name(semantic_summary, schema_overview)
        if semantic_table in schema_tables:
            return semantic_table

        if schema_tables:
            return schema_tables[0]

        raise HTTPException(
            status_code=422,
            detail={"message": "No table metadata was available to generate a safe SQL query."},
        )

    def _extract_table_name(self, semantic_summary: str, schema_overview: list[dict[str, Any]]) -> str:
        for line in semantic_summary.splitlines():
            if "->" in line and "." in line:
                right_side = line.split("->", maxsplit=1)[1].strip()
                return right_side.split(".", maxsplit=1)[0]
        if schema_overview:
            return str(schema_overview[0]["table"])
        raise HTTPException(
            status_code=422,
            detail={"message": "No table metadata was available to generate a safe SQL query."},
        )

    def _build_cache_key(
        self,
        *,
        user_query: str,
        context: dict[str, Any],
        semantic_summary: str,
        table_hint: str | None,
    ) -> str:
        context_key = json.dumps(context, sort_keys=True, default=str)
        return f"{user_query.strip().lower()}|{semantic_summary}|{table_hint or 'none'}|{context_key}"
